version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  node-backend:
    working_dir: /app
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: .
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
    command: yarn dev
    ports:
      - 4000:4000
    depends_on:
      - db

volumes:
  db:
  node_modules:
